services:
  service-registry:
    build:
      context: .
      dockerfile: service-registry/Dockerfile
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - gradle_cache:/root/.gradle
      - gradle_build_cache:/app/.gradle
    networks:
      - efood-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders_user -d orders_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - efood-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - EUREKA_URL=http://service-registry:8081/eureka
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      service-registry:
        condition: service_healthy
    volumes:
      - gradle_cache:/root/.gradle
      - gradle_build_cache:/app/.gradle
    networks:
      - efood-network

  ms-orders:
    build:
      context: .
      dockerfile: ms-orders/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URL=http://service-registry:8081/eureka
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/orders_db
      - SPRING_DATASOURCE_USERNAME=orders_user
      - SPRING_DATASOURCE_PASSWORD=orders_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      service-registry:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - gradle_cache:/root/.gradle
      - gradle_build_cache:/app/.gradle
    networks:
      - efood-network

volumes:
  postgres_data:
  gradle_cache:
  gradle_build_cache:

networks:
  efood-network:
    driver: bridge